language: bash

services:
  - docker

install:
  - docker run -it -e BUCKET_NAME=$BUCKET_NAME -e DISTRIBUTION_ID=$DISTRIBUTION_ID -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY somrc/hugo-workshop-build /root/workshop-site-master/build-site.sh

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - nmagee@virginia.edu
